"""Adiciona coluna keycloak_id a usuarios

Revision ID: d31542ce1327
Revises: 
Create Date: 2025-08-18 13:52:54.378686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'd31542ce1327'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploads')
    op.drop_table('logs')
    op.alter_column('chats', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chats', 'data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('chats_usuario_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('mensagens', 'chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('mensagens', 'autor',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('mensagens', 'data_envio',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('mensagens_chat_id_fkey'), 'mensagens', type_='foreignkey')
    op.create_foreign_key(None, 'mensagens', 'chats', ['chat_id'], ['id'])
    op.add_column('usuarios', sa.Column('keycloak_id', sa.String(), nullable=False))
    op.alter_column('usuarios', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('usuarios', 'data_criacao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_keycloak_id'), 'usuarios', ['keycloak_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_keycloak_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.alter_column('usuarios', 'data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('usuarios', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('usuarios', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('usuarios', 'keycloak_id')
    op.drop_constraint(None, 'mensagens', type_='foreignkey')
    op.create_foreign_key(op.f('mensagens_chat_id_fkey'), 'mensagens', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mensagens', 'data_envio',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('mensagens', 'autor',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('mensagens', 'chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_usuario_id_fkey'), 'chats', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chats', 'data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chats', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('acao', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('detalhe', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('logs_usuario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('logs_pkey'))
    )
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nome_arquivo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('departamento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('qtd_chunks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_upload', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('uploads_usuario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('uploads_pkey'))
    )
    # ### end Alembic commands ###
